# .golangci.yml
run:
  # 忽略的文件或文件夹使用正则表达式进行定义
  skip-dirs:
    - "^vendor$"
    - "build/**"
    - "crd/**"
    - "hack/**"
    - "pkg/crd/clientset/**"
    - "pkg/crd/informers/**"
    - "pkg/crd/listers/**"
    - "proto/**"
  # 可以通过具体的错误信息或正则来忽略某些问题
  skip-files:
    - ".*_test\\.go"
linters-settings:
  # 针对特定的linters的设置
  errcheck:
    check-type-assertions: true
linters:
   enable:
     - govet
     - golint
   disable:
     - unused
   # ...其他的linter设置

issues:
  exclude-rules:
    - linters:
        - govet
      text: "composite literal uses unkeyed fields"

