name: GolangCI-Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  staticcheck:
    name: Run GolangCI-Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --config .golangci.yml

    - name: Run golangci-lint
      run: golangci-lint run
