name: Golangci-Lint
on:
  push:
    branches:
      - master
      - main
      - release/*
      - beta/*
  pull_request:
    branches:
      - master
      - main
      - release/*
      - beta/*

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    strategy:
      matrix:
        go: ['1.19']
        # [macos-latest, windows-latest]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - name: Get Last Commit SHA
        id: last_commit
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "LAST_COMMIT_SHA=${{ github.event.before }}" >> $GITHUB_ENV
          else
            echo "LAST_COMMIT_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          fi
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        if: env.CHANGED_GO_FILES
        with:
          version: v1.14
          args: --new-from-rev=${{ env.LAST_COMMIT_SHA }} --out-format=github-actions --verbose
