name: Go Analysis
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  staticcheck:
    name: Staticcheck Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19' # 或者你项目所用的Go版本
    - name: Install staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
    - name: Run staticcheck
      run: |
        staticcheck ./...
